### ISSUE TITLE
Multiple @extend rules in the same block don't process the second @extend correctly

### ISSUE THREAD

**Issue by jzarzeckis** [csstools/postcss-extend-rule#10]
```css
%foo {
  right: 0;
}

%bar {
  left: 0;
}

.baz {
  @extend %foo;
  @extend %bar;
}
```

Worked in 2.0.0, but doesn't generate correctly on 3.0.0.

**Comment by gnimmelf** [comment]
No nagging, but I had a go at this, and it's way above my head =/ so I hope someone else sees the need for this in the near future and has a go at it.

Cheers!

**Comment by kongxiangyan** [comment]
@jzarzeckis @gnimmelf  Just use `@extend` like this:

```scss
%foo {
  right: 0;
}

%bar {
  left: 0;
}

.baz {
  @extend %foo, %bar;
}
```

And by the way, you can only use `@extend` at your first line of rules, following is not allowed:

```scss
%foo {
  right: 0;
}

%bar {
  left: 0;
}

.baz {
  top: 0;
  @extend %foo, %bar;
}
```
