### ISSUE TITLE
Bootstrap global classes are not visible when using @extend

### ISSUE THREAD

**Issue by FrancoAguilera** [csstools/postcss-extend-rule#20]
I have this small sandbox project [vite-sandbox](https://github.com/FrancoAguilera/vite-sandbox), if you take a look at [HelloWorld.vue](https://github.com/FrancoAguilera/vite-sandbox/blob/main/src/components/HelloWorld.vue) you will see that for classes defined on the same "vue file style scope" the @extend will work, but for the global bootstrap CSS classes it won't 

e.g.: 

```css
/*this will work*/
.my-class { 
  color: red; 
  background: pink; 
} 

.my-btn { 
  @extend .my-class; 
}


/*this will not work*/
.my-other-btn { 
  @extend .btn; 
}
```
