### ISSUE TITLE
Version 3.x.x breaks pseudo selector extensions

### ISSUE THREAD

**Issue by fatlard1993** [csstools/postcss-extend-rule#8]
The following example works in 2.x.x and not in 3.x.x:

```
.test {
  display: none;
}

.thing:before {
  @extend .test;
}
```

**Comment by romainmenke** [comment]
This has since been fixed.

On the latest version I get : 

```css
.test {
	display: none;
}

.thing:before {
	display: none;
}
```
